2024-04-24 17:28:49,519 INFO    StreamThr :40053 [internal.py:wandb_internal():86] W&B internal server running at pid: 40053, started at: 2024-04-24 17:28:49.517887
2024-04-24 17:28:49,522 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status
2024-04-24 17:28:49,527 INFO    WriterThread:40053 [datastore.py:open_for_write():87] open: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/run-jy6xz65p.wandb
2024-04-24 17:28:49,528 DEBUG   SenderThread:40053 [sender.py:send():379] send: header
2024-04-24 17:28:49,565 DEBUG   SenderThread:40053 [sender.py:send():379] send: run
2024-04-24 17:28:50,230 INFO    SenderThread:40053 [dir_watcher.py:__init__():211] watching files in: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files
2024-04-24 17:28:50,230 INFO    SenderThread:40053 [sender.py:_start_run_threads():1124] run started: jy6xz65p with start time 1713950929.518506
2024-04-24 17:28:50,246 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: check_version
2024-04-24 17:28:50,246 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: check_version
2024-04-24 17:28:50,556 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: run_start
2024-04-24 17:28:50,564 DEBUG   HandlerThread:40053 [system_info.py:__init__():26] System info init
2024-04-24 17:28:50,564 DEBUG   HandlerThread:40053 [system_info.py:__init__():41] System info init done
2024-04-24 17:28:50,564 INFO    HandlerThread:40053 [system_monitor.py:start():194] Starting system monitor
2024-04-24 17:28:50,564 INFO    SystemMonitor:40053 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-24 17:28:50,564 INFO    HandlerThread:40053 [system_monitor.py:probe():214] Collecting system info
2024-04-24 17:28:50,565 DEBUG   HandlerThread:40053 [system_info.py:probe():150] Probing system
2024-04-24 17:28:50,566 INFO    SystemMonitor:40053 [interfaces.py:start():190] Started cpu monitoring
2024-04-24 17:28:50,567 INFO    SystemMonitor:40053 [interfaces.py:start():190] Started disk monitoring
2024-04-24 17:28:50,568 INFO    SystemMonitor:40053 [interfaces.py:start():190] Started gpuapple monitoring
2024-04-24 17:28:50,572 INFO    SystemMonitor:40053 [interfaces.py:start():190] Started memory monitoring
2024-04-24 17:28:50,577 INFO    SystemMonitor:40053 [interfaces.py:start():190] Started network monitoring
2024-04-24 17:28:50,578 DEBUG   HandlerThread:40053 [system_info.py:_probe_git():135] Probing git
2024-04-24 17:28:50,607 DEBUG   HandlerThread:40053 [system_info.py:_probe_git():143] Probing git done
2024-04-24 17:28:50,608 DEBUG   HandlerThread:40053 [system_info.py:probe():198] Probing system done
2024-04-24 17:28:50,608 DEBUG   HandlerThread:40053 [system_monitor.py:probe():223] {'os': 'macOS-14.2.1-arm64-arm-64bit', 'python': '3.10.13', 'heartbeatAt': '2024-04-24T09:28:50.565576', 'startedAt': '2024-04-24T09:28:49.506768', 'docker': None, 'cuda': None, 'args': ('--model_name_or_path', '/Users/a58/Downloads/pretrain_model/Qwen/Qwen1.5-0.5B-Chat', '--do_train', 'True', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '1', '--learning_rate', '5e-5', '--weight_decay', '0', '--max_grad_norm', '1.0', '--num_train_epochs', '1.0', '--block_size', '32', '--train_file', '/Users/a58/Downloads/my_test/data/data_sft/renting_data_train_7000_improved_prompting3.json', '--output_dir', '/Users/a58/Downloads/MoE_Train/outputs', '--overwrite_output_dir', '--logging_dir', '/Users/a58/Downloads/MoE_Train/outputs', '--save_strategy', 'epoch', '--save_total_limit', '1', '--logging_strategy', 'steps', '--logging_steps', '1', '--report_to', 'wandb', '--trust_remote_code', 'True', '--template', 'llama3', '--q_lora', 'False', '--use_lora', 'True', '--lora_r', '8', '--lora_alpha', '32', '--lora_dropout', '0.05', '--lora_target_modules', 'q_proj', 'v_proj', 'k_proj', 'o_proj', 'gate_proj', 'down_proj', 'up_proj'), 'state': 'running', 'program': '/Users/a58/Downloads/MoE_Train/finetune/run.py', 'codePathLocal': 'run.py', 'codePath': 'finetune/run.py', 'git': {'remote': 'https://github.com/Darrenzeng/MoE_Train.git', 'commit': 'f1f43f83852171df6bd535b6c39de48dca03c558'}, 'email': 'zengyufei@58.com', 'root': '/Users/a58/Downloads/MoE_Train', 'host': '58deMacBook-Pro-2.local', 'username': 'a58', 'executable': '/Users/a58/anaconda3/envs/llama_factory/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 13.368824005126953}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-04-24 17:28:50,608 INFO    HandlerThread:40053 [system_monitor.py:probe():224] Finished collecting system info
2024-04-24 17:28:50,608 INFO    HandlerThread:40053 [system_monitor.py:probe():227] Publishing system info
2024-04-24 17:28:50,608 DEBUG   HandlerThread:40053 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-04-24 17:28:51,244 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/conda-environment.yaml
2024-04-24 17:28:54,198 DEBUG   HandlerThread:40053 [system_info.py:_save_conda():222] Saving conda packages done
2024-04-24 17:28:54,200 INFO    HandlerThread:40053 [system_monitor.py:probe():229] Finished publishing system info
2024-04-24 17:28:54,204 DEBUG   SenderThread:40053 [sender.py:send():379] send: files
2024-04-24 17:28:54,204 INFO    SenderThread:40053 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-04-24 17:28:54,248 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/conda-environment.yaml
2024-04-24 17:28:54,248 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-metadata.json
2024-04-24 17:28:54,601 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: python_packages
2024-04-24 17:28:54,601 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: python_packages
2024-04-24 17:28:54,602 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:28:54,602 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:28:54,602 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:28:54,605 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:28:54,781 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:28:54,781 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:28:54,781 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:28:55,014 DEBUG   SenderThread:40053 [sender.py:send():379] send: telemetry
2024-04-24 17:28:55,014 DEBUG   SenderThread:40053 [sender.py:send():379] send: config
2024-04-24 17:28:55,015 DEBUG   SenderThread:40053 [sender.py:send():379] send: metric
2024-04-24 17:28:55,016 DEBUG   SenderThread:40053 [sender.py:send():379] send: telemetry
2024-04-24 17:28:55,016 DEBUG   SenderThread:40053 [sender.py:send():379] send: metric
2024-04-24 17:28:55,016 WARNING SenderThread:40053 [sender.py:send_metric():1341] Seen metric with glob (shouldn't happen)
2024-04-24 17:28:55,016 DEBUG   SenderThread:40053 [sender.py:send():379] send: telemetry
2024-04-24 17:28:55,248 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:28:55,248 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/requirements.txt
2024-04-24 17:28:55,939 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:28:55,939 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:28:55,939 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:28:57,291 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:28:57,694 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: partial_history
2024-04-24 17:28:57,695 DEBUG   SenderThread:40053 [sender.py:send():379] send: metric
2024-04-24 17:28:57,696 DEBUG   SenderThread:40053 [sender.py:send():379] send: metric
2024-04-24 17:28:57,696 DEBUG   SenderThread:40053 [sender.py:send():379] send: metric
2024-04-24 17:28:57,696 DEBUG   SenderThread:40053 [sender.py:send():379] send: metric
2024-04-24 17:28:57,696 DEBUG   SenderThread:40053 [sender.py:send():379] send: history
2024-04-24 17:28:57,696 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: summary_record
2024-04-24 17:28:57,697 INFO    SenderThread:40053 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-24 17:28:58,277 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:28:58,277 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:28:58,277 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:28:58,278 INFO    wandb-upload_0:40053 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2791, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-04-24 17:28:58,296 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-summary.json
2024-04-24 17:28:59,305 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:28:59,719 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:00,309 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:29:03,088 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:29:03,088 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:29:03,089 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:29:04,730 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:05,041 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: partial_history
2024-04-24 17:29:05,043 DEBUG   SenderThread:40053 [sender.py:send():379] send: history
2024-04-24 17:29:05,043 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: summary_record
2024-04-24 17:29:05,048 INFO    SenderThread:40053 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-24 17:29:05,338 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-summary.json
2024-04-24 17:29:06,341 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:29:06,449 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: partial_history
2024-04-24 17:29:06,451 DEBUG   SenderThread:40053 [sender.py:send():379] send: history
2024-04-24 17:29:06,451 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: summary_record
2024-04-24 17:29:06,452 INFO    SenderThread:40053 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-24 17:29:07,349 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-summary.json
2024-04-24 17:29:07,355 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:29:08,355 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:29:10,048 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:29:10,057 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:29:10,156 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:10,157 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:29:12,567 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:29:12,929 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:29:12,932 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:29:15,667 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:20,705 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:21,469 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/config.yaml
2024-04-24 17:29:24,743 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:29:24,744 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:29:24,799 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:29:27,070 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:32,087 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:37,133 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:39,742 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:29:39,742 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:29:39,805 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:29:40,398 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2024-04-24 17:29:40,402 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:29:40,403 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:29:43,024 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:48,074 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:50,587 DEBUG   SystemMonitor:40053 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-24 17:29:50,687 DEBUG   SenderThread:40053 [sender.py:send():379] send: telemetry
2024-04-24 17:29:50,819 DEBUG   SenderThread:40053 [sender.py:send():379] send: stats
2024-04-24 17:29:53,855 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:29:54,795 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/config.yaml
2024-04-24 17:29:54,805 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:29:54,805 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:29:54,815 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:30:00,109 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:00,294 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: partial_history
2024-04-24 17:30:00,297 DEBUG   SenderThread:40053 [sender.py:send():379] send: history
2024-04-24 17:30:00,297 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: summary_record
2024-04-24 17:30:00,298 INFO    SenderThread:40053 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-24 17:30:00,828 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-summary.json
2024-04-24 17:30:01,830 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:30:02,835 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:30:05,315 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:09,756 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:30:09,758 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:30:09,812 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:30:11,079 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:13,612 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:30:13,612 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:30:13,612 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:30:16,099 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:20,892 DEBUG   SenderThread:40053 [sender.py:send():379] send: stats
2024-04-24 17:30:21,926 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:24,792 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:30:24,795 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:30:24,843 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:30:26,252 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: partial_history
2024-04-24 17:30:26,258 DEBUG   SenderThread:40053 [sender.py:send():379] send: history
2024-04-24 17:30:26,259 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: summary_record
2024-04-24 17:30:26,261 INFO    SenderThread:40053 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-24 17:30:26,976 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-summary.json
2024-04-24 17:30:27,267 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:27,975 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:30:28,977 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:30:32,299 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:37,322 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:39,785 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:30:39,789 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:30:39,844 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:30:43,154 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:48,170 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:50,927 DEBUG   SenderThread:40053 [sender.py:send():379] send: stats
2024-04-24 17:30:53,942 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:30:54,773 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:30:54,774 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:30:54,828 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:30:59,140 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:04,167 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:09,187 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:09,798 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:31:09,800 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:31:09,834 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:31:15,141 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:20,185 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:20,962 DEBUG   SenderThread:40053 [sender.py:send():379] send: stats
2024-04-24 17:31:24,183 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/jy6xz65p/wandb-metadata.json?Expires=1714037334&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tn2HcjFLzNphMVaUeoxrBTZVfrjUw03pCJbN7gi8VMkt5xoxvRoQNipnbgd47VLr5uYrV5OvgCcpQ9SkHzF6On9bMvVX201qG1JggKG9FtRks4qbfLcIqLhwCC6qbvrkfNP96zgjOT1c%2BkWA%2FTVB6bKN%2FZkZELZfTy0QemgT0dFikqlcNHm0MefX53iShbVfyDXhV2p4W%2F51SQ0Y19oezC%2BrwzDUkt%2Fj7D1t3qOPkm9I0rqQRtyMFqk%2By1rUiJ2aGGeEiU8%2FzE0j%2BDAZ%2FdhggjmD0VfKTA30bSwFeHrBvlkkGU3e6OdGk6Byjum5%2F3RG5t%2FAkW4a67PIqW9Zlovoaw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-24 17:31:24,183 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2451'}
2024-04-24 17:31:24,183 ERROR   wandb-upload_0:40053 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-24 17:31:24,790 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: stop_status
2024-04-24 17:31:24,792 DEBUG   SenderThread:40053 [sender.py:send_request():406] send_request: stop_status
2024-04-24 17:31:24,839 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-24 17:31:26,079 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:31,108 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:34,983 INFO    memory    :40053 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-04-24 17:31:34,985 DEBUG   SystemMonitor:40053 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-24 17:31:34,985 DEBUG   SystemMonitor:40053 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-24 17:31:34,991 DEBUG   SenderThread:40053 [sender.py:send():379] send: stats
2024-04-24 17:31:36,309 INFO    Thread-17 :40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:31:37,000 DEBUG   HandlerThread:40053 [handler.py:handle_request():146] handle_request: status_report
2024-04-24 17:31:39,301 WARNING StreamThr :40053 [internal.py:is_dead():414] Internal process exiting, parent pid 37734 disappeared
2024-04-24 17:31:39,302 ERROR   StreamThr :40053 [internal.py:wandb_internal():152] Internal process shutdown.
2024-04-24 17:31:40,012 INFO    HandlerThread:40053 [handler.py:finish():866] shutting down handler
2024-04-24 17:31:40,012 INFO    SenderThread:40053 [sender.py:finish():1546] shutting down sender
2024-04-24 17:31:40,014 INFO    WriterThread:40053 [datastore.py:close():296] close: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/run-jy6xz65p.wandb
2024-04-24 17:31:40,014 INFO    HandlerThread:40053 [system_monitor.py:finish():203] Stopping system monitor
2024-04-24 17:31:40,014 INFO    HandlerThread:40053 [interfaces.py:finish():202] Joined cpu monitor
2024-04-24 17:31:40,015 INFO    HandlerThread:40053 [interfaces.py:finish():202] Joined disk monitor
2024-04-24 17:31:40,015 INFO    HandlerThread:40053 [interfaces.py:finish():202] Joined gpuapple monitor
2024-04-24 17:31:40,015 INFO    HandlerThread:40053 [interfaces.py:finish():202] Joined memory monitor
2024-04-24 17:31:40,015 INFO    HandlerThread:40053 [interfaces.py:finish():202] Joined network monitor
2024-04-24 17:31:42,276 INFO    SenderThread:40053 [dir_watcher.py:finish():358] shutting down directory watcher
2024-04-24 17:31:42,334 INFO    SenderThread:40053 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log
2024-04-24 17:31:42,334 INFO    SenderThread:40053 [dir_watcher.py:finish():388] scan: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files
2024-04-24 17:31:42,335 INFO    SenderThread:40053 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/requirements.txt requirements.txt
2024-04-24 17:31:42,335 INFO    SenderThread:40053 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/output.log output.log
2024-04-24 17:31:42,338 INFO    SenderThread:40053 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/config.yaml config.yaml
2024-04-24 17:31:42,338 INFO    SenderThread:40053 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-summary.json wandb-summary.json
2024-04-24 17:31:42,338 INFO    SenderThread:40053 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/conda-environment.yaml conda-environment.yaml
2024-04-24 17:31:42,338 INFO    SenderThread:40053 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240424_172849-jy6xz65p/files/wandb-metadata.json wandb-metadata.json
2024-04-24 17:31:42,338 INFO    SenderThread:40053 [file_pusher.py:finish():172] shutting down file pusher
2024-04-24 17:31:42,338 INFO    SenderThread:40053 [file_pusher.py:join():178] waiting for file pusher
2024-04-24 17:31:42,342 INFO    SenderThread:40053 [file_stream.py:finish():614] file stream finish called
2024-04-24 17:31:43,084 INFO    SenderThread:40053 [file_stream.py:finish():618] file stream finish is done
